# ????
server:
  port: 8761

# ???????? ??? ID
spring:
  application:
    name: discoveryservice

# ?? ??? discovery? ???? ?? ??? false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
